export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const DELETE = 'DELETE'
export const FETCH_ALL = 'FETCH_ALL'

export const CREATE_PARTNER = 'CREATE_PARTNER'
export const UPDATE_PARTNER = 'UPDATE_PARTNER'
export const DELETE_PARTNER = 'DELETE_PARTNER'
export const FETCH_PARTNERS = 'FETCH_PARTNER'

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'

export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const FETCH_TASKS = 'FETCH_TASKS'

export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const FETCH_EVENTS = 'FETCH_EVENTS'

export const CREATE_BUDGET = 'CREATE_BUDGET'
export const UPDATE_BUDGET = 'UPDATE_BUDGET'
export const DELETE_BUDGET = 'DELETE_BUDGET'
export const FETCH_BUDGETS = 'FETCH_BUDGETS'

export const CREATE_PAYROLL = 'CREATE_PAYROLL'
export const UPDATE_PAYROLL = 'UPDATE_PAYROLL'
export const DELETE_PAYROLL = 'DELETE_PAYROLL'
export const FETCH_PAYROLLS = 'FETCH_PAYROLLS'
